// gen_reference_oracle.mjs — Strudel reference-surface oracle.
//
//   cd tools/oracle && node gen_reference_oracle.mjs
//
// Strudel's `@strudel/reference` package re-exports the jsdoc `doc.json` built
// by `jsdoc` over `packages/`. That file is generated by Node tooling and is
// not checked in, so rather than depend on a jsdoc build this script
// reconstructs the same name surface by source-scanning the vendored Strudel
// packages for:
//
//   * jsdoc `@name` tags          — the documented functions/methods/controls
//                                    (exactly what doc.json keys on)
//   * jsdoc `@synonyms` tags       — documented aliases
//   * `register('x' | [..])`       — registered Pattern functions/methods
//   * `registerControl('x', ..)`   — control names + aliases (incl. the
//     `export const { a, b } = registerControl(...)` destructured exports, so
//     undocumented controls are still captured)
//
// The emitted `reference_golden.json` is compared against
// `rudel_lang::reference()` by `crates/rudel-lang/tests/reference_parity.rs`,
// which reports every documented Strudel name missing from Rudel and checks the
// gap against the checked-in intentional-difference allowlist.

import { writeFileSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGES = resolve(__dirname, '../../strudel/packages');

// Recursively collect every .mjs source file under packages/, skipping
// node_modules/dist/test files (jsdoc excludes the same).
function collectSources(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist' || entry === 'test') continue;
      out.push(...collectSources(full));
    } else if (/\.mjs$/.test(entry) && !/\.test\.mjs$/.test(entry)) {
      out.push(full);
    }
  }
  return out;
}

const files = collectSources(PACKAGES);

const names = new Set();
const controls = new Set();
// name -> sorted list of packages that define it (for the per-package API
// inventory). A name can be defined in more than one package.
const namePackages = new Map();

const isIdent = (name) => /^[A-Za-z_$][\w$]*$/.test(name);

// Top-level package directory a source file belongs to (`.../packages/<pkg>/...`).
const packageOf = (file) => {
  const norm = file.replace(/\\/g, '/');
  const m = norm.match(/\/packages\/([^/]+)\//);
  return m ? m[1] : 'unknown';
};

const splitList = (raw) =>
  raw
    .split(/[,\s]+/)
    .map((s) => s.replace(/^['"`]|['"`]$/g, ''))
    .filter(Boolean);

for (const file of files) {
  const code = readFileSync(file, 'utf8');
  const pkg = packageOf(file);

  // jsdoc names are bare identifiers; ignore namespaced (`Pattern#foo`) or
  // empty tokens that the loose regexes might catch.
  const addName = (name) => {
    if (!name) return;
    const trimmed = name.trim();
    if (!isIdent(trimmed)) return;
    names.add(trimmed);
    if (!namePackages.has(trimmed)) namePackages.set(trimmed, new Set());
    namePackages.get(trimmed).add(pkg);
  };
  const addControl = (name) => {
    const trimmed = (name || '').trim();
    if (isIdent(trimmed)) controls.add(trimmed);
    addName(trimmed);
  };

  // @name <ident>
  for (const m of code.matchAll(/@name\s+([A-Za-z_$][\w$]*)/g)) addName(m[1]);

  // @synonyms a, b, c
  for (const m of code.matchAll(/@synonyms\s+([^\n*]+)/g)) {
    for (const s of splitList(m[1])) addName(s);
  }

  // register('x', ...)  and  register(['x', 'y'], ...)
  for (const m of code.matchAll(/\bregister\(\s*'([^']+)'/g)) addName(m[1]);
  for (const m of code.matchAll(/\bregister\(\s*\[([^\]]*)\]/g)) {
    for (const s of splitList(m[1])) addName(s);
  }

  // export const { a, b } = registerControl(...)
  for (const m of code.matchAll(/const\s*\{([^}]*)\}\s*=\s*registerControl/g)) {
    for (const s of splitList(m[1])) addControl(s);
  }

  // registerControl('name', 'alias', ...)
  for (const m of code.matchAll(/\bregisterControl\(\s*'([^']+)'((?:\s*,\s*'[^']+')*)/g)) {
    addControl(m[1]);
    for (const s of m[2].match(/'([^']+)'/g) || []) addControl(s.replace(/'/g, ''));
  }
  // registerControl(['name', 'alias', ...], ...)
  for (const m of code.matchAll(/\bregisterControl\(\s*\[([^\]]*)\]/g)) {
    for (const s of splitList(m[1])) addControl(s);
  }
}

// name -> ["pkgA", "pkgB"] sorted, for stable output.
const packagesByName = Object.fromEntries(
  [...namePackages.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)).map(([name, set]) => [name, [...set].sort()]),
);

const out = {
  comment:
    'Generated by tools/oracle/gen_reference_oracle.mjs — Strudel reference name surface ' +
    '(jsdoc @name/@synonyms + register/registerControl). Do not edit by hand.',
  names: [...names].sort(),
  controls: [...controls].sort(),
  packagesByName,
};

const dest = resolve(__dirname, 'reference_golden.json');
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n');
console.log(
  `wrote ${dest}: ${out.names.length} names, ${out.controls.length} controls from ${files.length} files`,
);
