// gen_hydra_oracle.mjs — dump hydra-synth's glsl function table for the rudel
// parity oracle (crates/rudel-lang/tests/hydra_parity.rs).
//
//   cd tools/oracle && npm install --no-save hydra-synth@1.3.29 && node gen_hydra_oracle.mjs
//
// Unlike every other oracle here, this one does not read the vendored Strudel
// checkout: `@strudel/hydra` is a ~50-line loader that pulls hydra-synth from a
// CDN at runtime (`await import('https://unpkg.com/hydra-synth')`), so there is
// no hydra source in the Strudel tree to port against. The version below is the
// one `strudel/packages/hydra/package.json` declares, pinned here so the Rust
// side has a fixed reference rather than a moving CDN target.
//
// Each entry is one hydra function: its name, its composition type, and its
// inputs with their defaults. `glsl` is the raw GLSL body, kept so a human can
// diff a WGSL port against it; the Rust test compares the *signature* (name,
// type, input names/types/defaults), which is what a pattern actually depends
// on. Nothing here is executed — the table is plain data.

import { readFileSync } from 'node:fs';
import { writeJson } from './lib.mjs';

// hydra-synth's `exports` map publishes the glsl table but not its own
// package.json, so the version comes off disk rather than through a require.
const PINNED = JSON.parse(
  readFileSync(new URL('node_modules/hydra-synth/package.json', import.meta.url), 'utf8'),
).version;

const { default: glslFunctions } = await import('hydra-synth/src/glsl/glsl-functions.js');

// hydra's own composition rules, from the comment block at the top of
// glsl-functions.js. The Rust composer has to agree with this table or a chain
// folds into the wrong shader.
const TYPES = {
  src: { returns: 'vec4', args: ['vec2 _st'] },
  coord: { returns: 'vec2', args: ['vec2 _st'] },
  color: { returns: 'vec4', args: ['vec4 _c0'] },
  combine: { returns: 'vec4', args: ['vec4 _c0', 'vec4 _c1'] },
  combineCoord: { returns: 'vec2', args: ['vec2 _st', 'vec4 _c0'] },
};

const functions = glslFunctions().map((fn) => {
  if (!TYPES[fn.type]) {
    throw new Error(`${fn.name}: unknown composition type ${fn.type}`);
  }
  return {
    name: fn.name,
    type: fn.type,
    inputs: (fn.inputs ?? []).map((input) => ({
      name: input.name,
      type: input.type,
      // Defaults are numbers, or arrays for vec4 inputs (`color`). Anything
      // else would not survive JSON, so fail loudly rather than silently.
      default: input.default ?? null,
    })),
    glsl: fn.glsl,
  };
});

const byType = {};
for (const fn of functions) byType[fn.type] = (byType[fn.type] ?? 0) + 1;

writeJson(
  'hydra_golden.json',
  {
    comment:
      'hydra-synth glsl function table, pinned. Generated by gen_hydra_oracle.mjs; do not edit by hand.',
    version: PINNED,
    types: TYPES,
    counts: { total: functions.length, byType },
    functions,
  },
  2,
);

console.log(`hydra-synth ${PINNED}: ${functions.length} functions`);
for (const [type, count] of Object.entries(byType).sort()) {
  console.log(`  ${type}: ${count}`);
}
