// mini_parity.rs — structural parity oracle for the mini-notation parser.
//
// `mini_golden.json` holds the haps Strudel's real parser (@strudel/mini)
// produces for each pattern over cycles 0..3, generated by
// `tools/oracle/gen_mini_oracle.mjs`. Each pattern is re-parsed with
// rudel-mini, queried over the same window, and compared hap-for-hap
// (order-independent) on timespans and values.
// SPDX-License-Identifier: AGPL-3.0-or-later

mod common;
use common::{golden_rows, rudel_rows};

#[test]
fn mini_notation_matches_strudel() {
    const CYCLES: i64 = 3;
    let golden: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(include_str!("mini_golden.json")).expect("parse golden json");

    let mut failures = Vec::new();
    for (code, rows) in &golden {
        let want = golden_rows(rows.as_array().expect("array"));
        let pat = rudel_mini::parse(code).unwrap_or_else(|e| panic!("rudel parse {code:?}: {e:?}"));
        let got = rudel_rows(&pat, CYCLES);
        if got != want {
            failures.push(format!(
                "pattern {code:?}\n  strudel ({} haps): {:#?}\n  rudel   ({} haps): {:#?}",
                want.len(),
                want,
                got.len(),
                got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "mini-notation parity mismatches:\n{}",
        failures.join("\n\n")
    );
}
