// mini_parity.rs — structural parity oracle for the mini-notation parser.
//
// `mini_golden.json` holds, for each pattern, the haps Strudel's real parser
// (@strudel/mini) produces over cycles 0..3 plus the pattern's `_steps`,
// generated by `tools/oracle/gen_mini_oracle.mjs`. Each pattern is re-parsed
// with rudel-mini, queried over the same window, and compared hap-for-hap
// (order-independent) on timespans, values, and step count.
// SPDX-License-Identifier: AGPL-3.0-or-later

mod common;
use common::{canon_locs, golden_locs, golden_rows, rudel_rows};

#[test]
fn mini_notation_matches_strudel() {
    const CYCLES: i64 = 3;
    let golden: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(include_str!("mini_golden.json")).expect("parse golden json");

    let mut failures = Vec::new();
    for (code, entry) in &golden {
        let want = golden_rows(entry["haps"].as_array().expect("haps array"), true);
        let want_steps = match &entry["steps"] {
            serde_json::Value::String(s) => s.clone(),
            _ => "_".to_string(),
        };
        let pat = rudel_mini::parse(code).unwrap_or_else(|e| panic!("rudel parse {code:?}: {e:?}"));
        let got = rudel_rows(&pat, CYCLES, true);
        if got != want {
            failures.push(format!(
                "pattern {code:?}\n  strudel ({} haps): {:#?}\n  rudel   ({} haps): {:#?}",
                want.len(),
                want,
                got.len(),
                got
            ));
        }
        let got_steps = match pat.steps {
            Some(s) => format!("{}/{}", s.numer(), s.denom()),
            None => "_".to_string(),
        };
        if got_steps != want_steps {
            failures.push(format!(
                "pattern {code:?} steps: strudel {want_steps}, rudel {got_steps}"
            ));
        }
        let want_locs = canon_locs(golden_locs(&entry["locs"]));
        let got_locs = canon_locs(rudel_mini::leaf_locations(code).expect("leaf locations"));
        if got_locs != want_locs {
            failures.push(format!(
                "pattern {code:?} leaf locations: strudel [{want_locs}], rudel [{got_locs}]"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "mini-notation parity mismatches:\n{}",
        failures.join("\n\n")
    );
}
