// tonal_parity.rs — parity oracle for the tonal/xen transforms.
//
// `tonal_golden.json` holds the pitch output Strudel's @strudel/tonal +
// @strudel/xen produce for a set of labelled expressions (generated by
// tools/oracle/gen_tonal_oracle.mjs). Here each label is rebuilt with rudel-core
// and compared hap-for-hap over cycles 0..2: timing exactly, pitch with a
// tolerance. Note-name values are normalised to MIDI on both sides (rudel emits
// MIDI numbers; Strudel emits enharmonic note names — an intentional difference).
// SPDX-License-Identifier: AGPL-3.0-or-later

use rudel_core::{Frac, Pattern, Value, freq, i, n, note, note_to_midi};
use rudel_mini::parse;
use std::collections::BTreeMap;

fn p(code: &str) -> Pattern {
    parse(code).expect("parse")
}

fn vs(s: &str) -> Value {
    Value::Str(s.to_string())
}

fn vlist(xs: &[f64]) -> Value {
    Value::List(xs.iter().map(|x| Value::F64(*x)).collect())
}

/// A chord pattern whose values become `{chord, ...extras}` maps, so the voicing
/// controls (`dictionary`/`anchor`/`mode`/`offset`) can be set the way Strudel's
/// `chord(...).dict(...)...` control chain does.
fn chord_map(code: &str, extras: &[(&str, Value)]) -> Pattern {
    let extras: Vec<(String, Value)> = extras
        .iter()
        .map(|(k, v)| (k.to_string(), v.clone()))
        .collect();
    p(code).with_value(move |v| {
        let mut m = BTreeMap::new();
        m.insert("chord".to_string(), v);
        for (k, val) in &extras {
            m.insert(k.clone(), val.clone());
        }
        Value::Map(m)
    })
}

/// Rebuild the rudel pattern for a golden label (mirrors gen_tonal_oracle.mjs).
/// String scale/interval args are passed as `Value::Str` (pure, never mini-parsed)
/// to match Strudel's raw `reify`; only base step patterns use `parse`.
fn build(label: &str) -> Pattern {
    match label {
        // transpose / trans
        "transpose_num" => note(p("c4 e4 g4")).transpose(7),
        "transpose_interval" => note(p("c4 e4 g4")).transpose(vs("3M")),
        "transpose_interval_neg" => note(p("c3 c4")).transpose(vs("-2M")),
        "transpose_bare_num" => p("0 4 7").transpose(12),
        "transpose_bare_interval" => p("0 4 7").transpose(vs("5P")),
        "transpose_pat" => note(p("c4 e4")).transpose(p("<0 7>")),

        // scale
        "scale_major" => n(p("0 1 2 3 4 5 6 7")).scale(vs("C:major")),
        "scale_minor" => n(p("0 2 4 7")).scale(vs("A:minor")),
        "scale_root_oct" => n(p("0 7 -1")).scale(vs("C4:major")),
        "scale_neg" => n(p("-1 -2 -7")).scale(vs("C:major")),
        "scale_sharps_flats" => n(p("0 1b 4#")).scale(vs("C:major")),
        "scale_pentatonic" => n(p("0 1 2 3 4 5")).scale(vs("C:minor:pentatonic")),
        "scale_chromatic" => n(p("0 1 2 3 11")).scale(vs("C:chromatic")),
        "scale_bebop" => n(p("0 1 2 3 4 5 6 7")).scale(vs("C:bebop:major")),
        "scale_quantize_tie" => note(p("c#3 d#3 f#3")).scale(vs("C:major")),
        "scale_quantize_octave" => note(p("b3 b4")).scale(vs("C:major:pentatonic")),
        "scale_pat" => n(p("0 2 4")).scale(p("<C:major A:minor>")),

        // scaleTranspose / scaleTrans / strans
        "strans_pos" => n(p("0 1 2")).scale(vs("C:major")).scale_transpose(2),
        "strans_neg" => n(p("0 2 4")).scale(vs("C:major")).scale_transpose(-1),
        "strans_pat" => n(p("0 2 4"))
            .scale(vs("C:major"))
            .scale_transpose(p("<0 -2>")),

        // xen
        "xen_edo31" => i(p("0 8 18")).xen(vs("31edo")),
        "xen_edo12" => i(p("0 3 7 12")).xen(vs("12edo")),
        "xen_ratios" => i(p("0 1 2")).xen(vlist(&[1.0, 5.0 / 4.0, 3.0 / 2.0])),
        "xen_ji" => i(p("0 1 2 3 4 5")).xen(vs("12ji")),
        "xen_tune_name" => i(p("0 1 2 3 4 5")).xen(vs("hexany15")),
        "xen_neg" => i(p("-1 -2")).xen(vlist(&[1.0, 5.0 / 4.0, 3.0 / 2.0])),
        "xen_pat" => i(p("0 1 2")).xen(p("<5edo 12edo>")),

        // withBase
        "withbase_num" => i(p("0 3 7")).xen(vs("12edo")).with_base(440.0),
        "withbase_pair" => i(p("0 3"))
            .xen(vs("12edo"))
            .with_base(vlist(&[440.0, 110.0])),

        // ftrans / ftranspose
        "ftrans_ctx" => i(p("0 8 18")).xen(vs("31edo")).ftrans(7),
        "ftrans_explicit" => freq(p("200 300")).ftrans(vlist(&[7.0, 31.0])),
        "ftrans_default12" => freq(p("200 400")).ftrans(7),
        "ftrans_step_edo" => i(p("0 7")).xen(vs("31edo")).ftrans(p("1:12")),
        "ftrans_pat" => i(p("0 8")).xen(vs("31edo")).ftrans(p("<8 -8>")),

        // tuning
        "tuning_ratios" => p("0 1 2 3").tuning(vlist(&[1.0, 5.0 / 4.0, 3.0 / 2.0])),

        // tune
        "tune_name" => i(p("0 1 2 3 4 5")).tune(vs("hexany15")),
        "tune_array" => i(p("0 1 2")).tune(vlist(&[
            261.625_565_300_6,
            302.729_620_128_27,
            350.291_542_792_12,
        ])),

        // voicing
        "voicing_default" => p("<C^7 A7 Dm7 G7>").voicing(),
        "voicing_ireal_ext" => p("C^7 Am7").voicings("ireal-ext"),
        "voicing_lefthand" => p("C^7 A7 Dm7 G7").voicings("lefthand"),
        "voicing_triads" => p("C Am F G").voicings("triads"),
        "voicing_guidetones" => p("C^7 Dm7").voicings("guidetones"),
        "voicing_legacy" => p("C^7 Am7").voicings("legacy"),
        "voicing_anchor" => chord_map("C^7 Dm7", &[("anchor", vs("c5"))]).voicing(),
        "voicing_mode_above" => chord_map(
            "C^7 Dm7",
            &[("dictionary", vs("lefthand")), ("mode", vs("above"))],
        )
        .voicing(),
        "voicing_offset" => chord_map(
            "C^7 Dm7",
            &[("dictionary", vs("lefthand")), ("offset", Value::Int(1))],
        )
        .voicing(),
        // n("0 1 2 3").chord("C^7").voicing(): n comes from the base pattern.
        "voicing_n" => p("0 1 2 3")
            .with_value(|v| {
                let mut m = BTreeMap::new();
                m.insert("n".to_string(), v);
                m.insert("chord".to_string(), Value::Str("C^7".to_string()));
                Value::Map(m)
            })
            .voicing(),

        // rootNotes
        "rootnotes2" => p("<C^7 A7 Dm7 G7>").root_notes(2),
        "rootnotes3" => p("Cm7 F#maj7 Bb7").root_notes(3),

        // xenharmonic doc examples
        "xen_doc_mixed" => i(p("0 1 2 3 4 5 6 7")).xen(p("<5edo 10edo 15edo hexany15>")),
        "withbase_doc_patterned" => i(p("[0 1 2 3] [3 4] [4 3 2 1]"))
            .xen(vs("hexany23"))
            .with_base(p("<220 [300 200]>")),
        "ftrans_doc_alt" => i(p("0 7 8 18")).xen(vs("31edo")).ftrans(p("<0 1:31 1:12>")),
        "ftrans_doc_freq" => freq(p("200 300 400")).ftrans(p("<0 7:31 7>")),
        "tune_doc_tranh3" => i(p("4 8 9 10 5 7 9 11")).tune(vs("tranh3")),

        // edoScale
        "edo_12edo_bare" => p("0 2 4 6").edo_scale(vs("C:LLsLLLs:2:1")),
        "edo_16edo_bare" => p("0 1 2 3 4 5 6").edo_scale(vs("C:LLsLLL:3:1")),
        "edo_wrap" => p("7 8 9 13").edo_scale(vs("C:LLsLLLs:2:1")),
        "edo_obj_freq" => n(p("0 2 4")).edo_scale(vs("C:LLsLLLs:2:1")),
        "edo_alt_def" => p("0 1 2").edo_scale(p("<C:LLsLLLs:2:1 C:LLsLLL:3:1>")),

        other => panic!("unknown golden label {other:?}"),
    }
}

const CYCLES: i64 = 2;
const EPS: f64 = 1e-4;

fn note_num(v: &Value) -> f64 {
    match v {
        Value::Str(s) => note_to_midi(s).map(|m| m as f64).unwrap_or(f64::NAN),
        other => other.as_f64().unwrap_or(f64::NAN),
    }
}

/// Reduce a rudel hap value to a (kind, number) pitch descriptor, matching the
/// `norm` in gen_tonal_oracle.mjs (`note`/bare-number both collapse to `pitch`).
fn norm(v: &Value) -> (&'static str, f64) {
    match v {
        Value::Map(m) => {
            if let Some(f) = m.get("freq").and_then(Value::as_f64) {
                ("freq", f)
            } else if let Some(nv) = m.get("note") {
                ("pitch", note_num(nv))
            } else if let Some(nv) = m.get("n") {
                ("pitch", note_num(nv))
            } else {
                ("other", 0.0)
            }
        }
        other => ("pitch", other.as_f64().unwrap_or(f64::NAN)),
    }
}

fn frac_str(f: Frac) -> String {
    format!("{}/{}", f.numer(), f.denom())
}

/// A sortable row: (timing+kind key, pitch). Sorting includes the pitch so equal
/// keys still line up deterministically across the two sides.
fn rudel_rows(pat: &Pattern) -> Vec<(String, f64)> {
    let mut rows: Vec<(String, f64)> = pat
        .query_arc(Frac::zero(), Frac::int(CYCLES))
        .into_iter()
        .map(|h| {
            let (wb, we) = match h.whole {
                Some(w) => (frac_str(w.begin), frac_str(w.end)),
                None => ("null".to_string(), "null".to_string()),
            };
            let (kind, x) = norm(&h.value);
            let key = format!(
                "{}|{}|{}|{}|{}",
                frac_str(h.part.begin),
                frac_str(h.part.end),
                wb,
                we,
                kind
            );
            (key, x)
        })
        .collect();
    rows.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.total_cmp(&b.1)));
    rows
}

fn golden_rows(rows: &[serde_json::Value]) -> Vec<(String, f64)> {
    let cell = |r: &serde_json::Value, k: &str| match &r[k] {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Null => "null".to_string(),
        other => other.to_string(),
    };
    let mut out: Vec<(String, f64)> = rows
        .iter()
        .map(|r| {
            let key = format!(
                "{}|{}|{}|{}|{}",
                cell(r, "pb"),
                cell(r, "pe"),
                cell(r, "wb"),
                cell(r, "we"),
                cell(r, "k"),
            );
            let x = r["x"].as_f64().unwrap_or(f64::NAN);
            (key, x)
        })
        .collect();
    out.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.total_cmp(&b.1)));
    out
}

#[test]
fn tonal_and_xen_match_strudel() {
    let golden: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(include_str!("tonal_golden.json")).expect("parse golden json");

    let mut failures = Vec::new();
    for (label, rows) in &golden {
        let want = golden_rows(rows.as_array().expect("array"));
        let got = rudel_rows(&build(label));
        let mut ok = want.len() == got.len();
        if ok {
            for (a, b) in got.iter().zip(&want) {
                if a.0 != b.0 || (a.1 - b.1).abs() > EPS {
                    ok = false;
                    break;
                }
            }
        }
        if !ok {
            failures.push(format!(
                "tonal {label:?}\n  strudel ({} haps): {:?}\n  rudel   ({} haps): {:?}",
                want.len(),
                want,
                got.len(),
                got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "tonal/xen parity mismatches:\n{}",
        failures.join("\n\n")
    );
}
