// transform_parity.rs — structural parity oracle for core transforms.
//
// `core_golden.json` holds the haps Strudel's engine produces for a set of
// labelled transform expressions (generated by tools/oracle/gen_core_oracle.mjs).
// Here each label is rebuilt with rudel-core and compared hap-for-hap over
// cycles 0..4. The base patterns are the same mini strings used on the JS side.
// SPDX-License-Identifier: AGPL-3.0-or-later

mod common;
use common::{golden_rows, rudel_rows};
use rudel_core::{Frac, Pattern, note, s};
use rudel_mini::parse;

fn p(code: &str) -> Pattern {
    parse(code).expect("parse")
}

/// Rebuild the rudel pattern for a golden label (mirrors gen_core_oracle.mjs).
fn build(label: &str) -> Pattern {
    match label {
        "rev" => p("0 1 2 3").rev(),
        "fast2" => p("0 1 2 3").fast(2),
        "slow2" => p("0 1 2 3").slow(2),
        "ply2" => p("0 1 2").ply(2),
        "iter4" => p("0 1 2 3").iter(4),
        "palindrome" => p("0 1 2").palindrome(),
        "every2_add10" => p("0 1 2 3").every(2, |x| x.add(10)),
        "off_add12" => p("0 1").off(0.25, |x| x.add(12)),
        "chop2" => s(p("bd")).chop(2),
        "striate2" => s(p("bd sd")).striate(2),
        "chunk4_add10" => p("0 1 2 3").chunk(4, |x| x.add(10)),
        "within_add10" => p("0 1 2 3").within(Frac::zero(), Frac::new(1, 2), |x| x.add(10)),
        "struct" => p("0").struct_pat(p("1 0 1 0")),
        "mask" => p("0 1 2 3").mask(p("1 0")),
        "jux_rev" => note(p("0 1")).jux(|x| x.rev()),
        "add_const" => p("0 1 2").add(10),
        "degrade" => p("0 1 2 3 4 5 6 7").degrade_by(0.5),
        "superimpose" => p("0 1").superimpose(|x| x.add(7)),
        other => panic!("unknown golden label {other:?}"),
    }
}

#[test]
fn transforms_match_strudel() {
    const CYCLES: i64 = 4;
    let golden: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(include_str!("core_golden.json")).expect("parse golden json");

    let mut failures = Vec::new();
    for (label, rows) in &golden {
        let want = golden_rows(rows.as_array().expect("array"));
        let got = rudel_rows(&build(label), CYCLES);
        if got != want {
            failures.push(format!(
                "transform {label:?}\n  strudel ({} haps): {:#?}\n  rudel   ({} haps): {:#?}",
                want.len(),
                want,
                got.len(),
                got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "transform parity mismatches:\n{}",
        failures.join("\n\n")
    );
}
