// transform_parity.rs — structural parity oracle for core transforms.
//
// `core_golden.json` holds the haps Strudel's engine produces for a set of
// labelled transform expressions (generated by tools/oracle/gen_core_oracle.mjs).
// Here each label is rebuilt with rudel-core and compared hap-for-hap over
// cycles 0..4. The base patterns are the same mini strings used on the JS side.
// SPDX-License-Identifier: AGPL-3.0-or-later

mod common;
use common::{golden_rows, rudel_rows};
use rudel_core::{Frac, Pattern, PickJoin, note, pick_list, pick_map, randrun, s, zip};
use rudel_mini::parse;
use std::collections::HashMap;

fn p(code: &str) -> Pattern {
    parse(code).expect("parse")
}

fn pmap(entries: &[(&str, &str)]) -> HashMap<String, Pattern> {
    entries.iter().map(|(k, v)| (k.to_string(), p(v))).collect()
}

/// Rebuild the rudel pattern for a golden label (mirrors gen_core_oracle.mjs).
fn build(label: &str) -> Pattern {
    match label {
        "rev" => p("0 1 2 3").rev(),
        "fast2" => p("0 1 2 3").fast(2),
        "slow2" => p("0 1 2 3").slow(2),
        "ply2" => p("0 1 2").ply(2),
        "iter4" => p("0 1 2 3").iter(4),
        "palindrome" => p("0 1 2").palindrome(),
        "every2_add10" => p("0 1 2 3").every(2, |x| x.add(10)),
        "off_add12" => p("0 1").off(0.25, |x| x.add(12)),
        "chop2" => s(p("bd")).chop(2),
        "striate2" => s(p("bd sd")).striate(2),
        "chunk4_add10" => p("0 1 2 3").chunk(4, |x| x.add(10)),
        "within_add10" => p("0 1 2 3").within(Frac::zero(), Frac::new(1, 2), |x| x.add(10)),
        "struct" => p("0").struct_pat(p("1 0 1 0")),
        "mask" => p("0 1 2 3").mask(p("1 0")),
        "jux_rev" => note(p("0 1")).jux(|x| x.rev()),
        "add_const" => p("0 1 2").add(10),
        "degrade" => p("0 1 2 3 4 5 6 7").degrade_by(0.5),
        "superimpose" => p("0 1").superimpose(|x| x.add(7)),
        "add_out" => p("0 1").add_out(p("10 20 30")),
        "add_mix" => p("0 1 2").add_mix(p("10 20")),
        "add_squeeze" => p("0 1").add_squeeze(p("10 20")),
        "add_squeezeout" => p("0 1").add_squeezeout(p("10 20")),
        "add_reset" => p("0 10 20 30").add_reset(p("0 100")),
        "add_restart" => p("0 10 20 30").add_restart(p("0 100")),
        "mul_out" => p("1 2").mul_out(p("10 20 30")),
        "set_squeeze" => note(p("0 1")).set_squeeze(s(p("a b"))),
        "set_out" => note(p("0 1")).set_out(s(p("a b c"))),
        "keep_out" => note(p("0 1")).keep_out(s(p("a b c"))),
        "add_poly" => p("0 1 2").add_poly(p("10 20")),
        "set_poly" => note(p("0 1 2")).set_poly(s(p("a b"))),
        "randrun8" => randrun(8),
        "shuffle4" => p("0 1 2 3").shuffle(4),
        "shuffle2" => p("a b c d").shuffle(2),
        "scramble4" => p("0 1 2 3").scramble(4),
        "tour" => p("[c g]").tour(&[p("e f"), p("e f g"), p("g f e c")]),
        "zip" => zip(&[p("e f"), p("e f g"), p("g [f e] a f4 c")]),
        "pick" => pick_list(
            &[p("g a"), p("e f"), p("f g f g"), p("g c d")],
            &p("<0 1 2 3>"),
            false,
            PickJoin::Inner,
        ),
        "pick_clamp" => pick_list(&[p("a"), p("b c")], &p("0 1 5"), false, PickJoin::Inner),
        "pickmod_wrap" => pick_list(&[p("a"), p("b c")], &p("0 1 5"), true, PickJoin::Inner),
        "pick_out" => pick_list(&[p("a b c"), p("d e")], &p("0 1"), false, PickJoin::Outer),
        "pickmod_out" => pick_list(&[p("a b c"), p("d e")], &p("0 5"), true, PickJoin::Outer),
        "pick_reset" => pick_map(
            &pmap(&[("a", "<0 1>"), ("b", "<2 3> 4")]),
            &p("a [~ b]"),
            PickJoin::Reset,
        ),
        "pick_restart" => pick_map(
            &pmap(&[("a", "<0 1>"), ("b", "<2 3> 4")]),
            &p("a [~ b]"),
            PickJoin::Restart,
        ),
        "inhabit" => pick_list(
            &[p("x y"), p("z w v")],
            &p("<0 1 [0 1]>"),
            false,
            PickJoin::Squeeze,
        ),
        "inhabit_map" => pick_map(
            &pmap(&[("a", "0 1 2"), ("b", "3 4")]),
            &p("a@2 [a b] a"),
            PickJoin::Squeeze,
        ),
        "inhabitmod_wrap" => pick_list(&[p("x y"), p("z")], &p("0 5"), true, PickJoin::Squeeze),
        // standalone squeeze(pat, xs) == inhabitmod restricted to lists
        "squeeze" => pick_list(
            &[p("g a"), p("f g f g"), p("g a c d")],
            &p("<0@2 [1!2] 2>"),
            true,
            PickJoin::Squeeze,
        ),
        // pickF == pick among the eagerly applied results (inner join)
        "pickF" => {
            let base = s(p("bd [rim hh]"));
            pick_list(
                &[base.rev(), base.jux(|x| x.rev()), base.fast(2)],
                &p("<0 1 2>"),
                false,
                PickJoin::Inner,
            )
        }
        "pickmodF" => {
            let base = s(p("bd [rim hh]"));
            pick_list(
                &[base.rev(), base.jux(|x| x.rev()), base.fast(2)],
                &p("<0 1 5>"),
                true,
                PickJoin::Inner,
            )
        }
        other => panic!("unknown golden label {other:?}"),
    }
}

#[test]
fn transforms_match_strudel() {
    const CYCLES: i64 = 4;
    let golden: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(include_str!("../../../tools/oracle/core_golden.json"))
            .expect("parse golden json");

    let mut failures = Vec::new();
    for (label, rows) in &golden {
        let want = golden_rows(rows.as_array().expect("array"), false);
        let got = rudel_rows(&build(label), CYCLES, false);
        if got != want {
            failures.push(format!(
                "transform {label:?}\n  strudel ({} haps): {:#?}\n  rudel   ({} haps): {:#?}",
                want.len(),
                want,
                got.len(),
                got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "transform parity mismatches:\n{}",
        failures.join("\n\n")
    );
}
