//! The editor's themes: TOML files, one per theme. Strudel's are built in
//! (`themes/*.toml`, generated by `tools/generate_themes.mjs` and embedded by
//! `build.rs`); a user's own are read at launch from rudel's themes folder
//! ([`user_dir`]), where one with a built-in theme's name replaces it.
//!
//! A theme file:
//!
//! ```toml
//! name = "midnight"        # optional: the file name otherwise
//! light = false            # optional: whether visualisers draw dark on light
//! background = "#101020"   # required
//! foreground = "#e0e0ff"   # required
//! keyword = "#ff79c6"      # every other colour is optional
//! ```
//!
//! Colours are `#rgb`, `#rgba`, `#rrggbb` or `#rrggbbaa`. A colour left out
//! comes from the others, as the generator derives Strudel's.

use std::{path::Path, sync::OnceLock};

include!(concat!(env!("OUT_DIR"), "/builtin_themes.rs"));

/// One theme: the `settings` `@strudel/draw` paints with, and the syntax
/// colours rudel's highlighter has a token for.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct ThemeData {
    pub(crate) name: String,
    pub(crate) light: bool,
    pub(crate) background: [u8; 4],
    pub(crate) line_background: [u8; 4],
    pub(crate) foreground: [u8; 4],
    pub(crate) muted: [u8; 4],
    pub(crate) caret: [u8; 4],
    pub(crate) selection: [u8; 4],
    pub(crate) selection_match: [u8; 4],
    pub(crate) line_highlight: [u8; 4],
    pub(crate) gutter_background: [u8; 4],
    pub(crate) gutter_foreground: [u8; 4],
    pub(crate) keyword: [u8; 4],
    /// `propertyName`: the `.fast` of a method call.
    pub(crate) method: [u8; 4],
    pub(crate) string: [u8; 4],
    pub(crate) number: [u8; 4],
    pub(crate) comment: [u8; 4],
    /// `punctuation`: mini-notation's `[ ] < > * /`.
    pub(crate) mini_op: [u8; 4],
    pub(crate) mini_word: [u8; 4],
}

/// `#rgb`, `#rgba`, `#rrggbb` or `#rrggbbaa`.
fn colour(text: &str) -> Option<[u8; 4]> {
    let hex = text.strip_prefix('#')?;
    let digits: String = match hex.len() {
        3 | 4 => hex.chars().flat_map(|c| [c, c]).collect(),
        6 | 8 => hex.to_string(),
        _ => return None,
    };
    let byte = |i: usize| u8::from_str_radix(digits.get(i..i + 2)?, 16).ok();
    Some([
        byte(0)?,
        byte(2)?,
        byte(4)?,
        if digits.len() == 8 { byte(6)? } else { 255 },
    ])
}

/// A theme from a file's text; `file_name` names it when the file does not.
pub(crate) fn parse(file_name: &str, text: &str) -> Result<ThemeData, String> {
    let table: toml::Table = text
        .parse()
        .map_err(|e: toml::de::Error| e.message().to_string())?;
    let get = |key: &str| -> Result<Option<[u8; 4]>, String> {
        match table.get(key) {
            None => Ok(None),
            Some(toml::Value::String(text)) => colour(text)
                .map(Some)
                .ok_or_else(|| format!("{key} = {text:?} is not a #rrggbb colour")),
            Some(other) => Err(format!("{key} should be a \"#rrggbb\" string, not {other}")),
        }
    };
    let need = |key: &str| get(key)?.ok_or_else(|| format!("{key} is missing"));
    let alpha = |[r, g, b, _]: [u8; 4], a: u8| [r, g, b, a];
    let background = need("background")?;
    let foreground = need("foreground")?;
    let muted = get("muted")?.unwrap_or(alpha(foreground, 0x50));
    let string = get("string")?.unwrap_or(foreground);
    let stem = file_name.strip_suffix(".toml").unwrap_or(file_name);
    Ok(ThemeData {
        name: match table.get("name") {
            Some(toml::Value::String(name)) => name.clone(),
            None => stem.to_string(),
            Some(other) => return Err(format!("name should be a string, not {other}")),
        },
        light: match table.get("light") {
            Some(toml::Value::Boolean(light)) => *light,
            None => false,
            Some(other) => return Err(format!("light should be true or false, not {other}")),
        },
        background,
        line_background: get("line_background")?.unwrap_or(alpha(background, 0x99)),
        foreground,
        muted,
        caret: get("caret")?.unwrap_or(foreground),
        selection: get("selection")?.unwrap_or(alpha(foreground, 0x40)),
        selection_match: get("selection_match")?.unwrap_or(alpha(foreground, 0x26)),
        line_highlight: get("line_highlight")?.unwrap_or(alpha(foreground, 0x1a)),
        gutter_background: get("gutter_background")?.unwrap_or([0, 0, 0, 0]),
        gutter_foreground: get("gutter_foreground")?.unwrap_or(muted),
        keyword: get("keyword")?.unwrap_or(foreground),
        method: get("method")?.unwrap_or(foreground),
        string,
        number: get("number")?.unwrap_or(foreground),
        comment: get("comment")?.unwrap_or(muted),
        mini_op: get("mini_op")?.unwrap_or(foreground),
        mini_word: get("mini_word")?.unwrap_or(string),
    })
}

/// The built-in themes, then each of `user` (file name and text) that reads,
/// replacing a theme of the same name; sorted by name. Also what did not read.
fn merge(user: Vec<(String, String)>) -> (Vec<ThemeData>, Vec<String>) {
    let mut themes: Vec<ThemeData> = BUILTIN
        .iter()
        .map(|(file, text)| parse(file, text).unwrap_or_else(|e| panic!("built-in {file}: {e}")))
        .collect();
    let mut errors = Vec::new();
    for (file, text) in user {
        match parse(&file, &text) {
            Ok(theme) => match themes.iter_mut().find(|t| t.name == theme.name) {
                Some(same) => *same = theme,
                None => themes.push(theme),
            },
            Err(e) => errors.push(format!("theme {file}: {e}")),
        }
    }
    themes.sort_by_key(|t| t.name.to_lowercase());
    (themes, errors)
}

static THEMES: OnceLock<Vec<ThemeData>> = OnceLock::new();

/// Every theme. The built-in ones only, unless [`load_user`] ran first.
pub(crate) fn all() -> &'static [ThemeData] {
    THEMES.get_or_init(|| merge(Vec::new()).0)
}

/// Where a user's own themes go: `themes` beside rudel's saved data
/// (`%APPDATA%\rudel\themes` on Windows).
pub(crate) fn user_dir() -> Option<std::path::PathBuf> {
    let data = eframe::storage_dir("rudel")?;
    let base = if data.ends_with("data") {
        data.parent()?.to_path_buf()
    } else {
        data
    };
    Some(base.join("themes"))
}

/// Add the themes in `dir` to the built-in ones. Called once at launch, before
/// anything asks for a theme; returns what did not read, to show the user.
pub(crate) fn load_user(dir: &Path) -> Vec<String> {
    let mut files: Vec<(String, String)> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "toml"))
        .filter_map(|path| {
            let name = path.file_name()?.to_string_lossy().into_owned();
            Some((name, std::fs::read_to_string(&path).ok()?))
        })
        .collect();
    files.sort();
    let (themes, errors) = merge(files);
    // ponytail: themes are fixed for the session; a "reload themes" would
    // need EditorTheme to hold a name rather than an index into this list.
    let _ = THEMES.set(themes);
    errors
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_built_in_theme_reads_and_strudel_s_own_is_there() {
        let (themes, errors) = merge(Vec::new());
        assert!(errors.is_empty(), "{errors:?}");
        assert_eq!(themes.len(), BUILTIN.len());
        assert!(themes.iter().any(|t| t.name == "strudelTheme"));
    }

    #[test]
    fn colours_read_in_every_css_hex_form() {
        assert_eq!(colour("#abc"), Some([0xaa, 0xbb, 0xcc, 255]));
        assert_eq!(colour("#abcd"), Some([0xaa, 0xbb, 0xcc, 0xdd]));
        assert_eq!(colour("#102030"), Some([0x10, 0x20, 0x30, 255]));
        assert_eq!(colour("#10203040"), Some([0x10, 0x20, 0x30, 0x40]));
        for bad in ["102030", "#12345", "#gggggg", "#ééé", "red"] {
            assert_eq!(colour(bad), None, "{bad}");
        }
    }

    #[test]
    fn a_minimal_theme_fills_in_the_rest() {
        let theme = parse("mine.toml", "background = \"#000\"\nforeground = \"#fff\"").unwrap();
        assert_eq!(theme.name, "mine");
        assert!(!theme.light);
        assert_eq!(theme.muted, [255, 255, 255, 0x50]);
        assert_eq!(theme.comment, theme.muted);
        assert_eq!(theme.line_background, [0, 0, 0, 0x99]);
        assert_eq!(theme.mini_word, theme.foreground);
    }

    #[test]
    fn a_bad_theme_says_what_is_wrong() {
        let err = |text: &str| parse("x.toml", text).unwrap_err();
        assert!(err("foreground = \"#fff\"").contains("background is missing"));
        assert!(err("background = \"#000\"\nforeground = \"white\"").contains("foreground"));
        assert!(err("background = 3\nforeground = \"#fff\"").contains("background should be"));
        assert!(!err("background = [").is_empty(), "not TOML");
    }

    #[test]
    fn a_user_theme_adds_to_or_replaces_the_built_in_ones() {
        let (themes, errors) = merge(vec![
            (
                "dracula.toml".into(),
                "background = \"#000\"\nforeground = \"#fff\"".into(),
            ),
            (
                "midnight.toml".into(),
                "background = \"#000\"\nforeground = \"#fff\"".into(),
            ),
            ("broken.toml".into(), "background = \"#000\"".into()),
        ]);
        assert_eq!(themes.len(), BUILTIN.len() + 1);
        let dracula = themes.iter().find(|t| t.name == "dracula").unwrap();
        assert_eq!(dracula.background, [0, 0, 0, 255]);
        assert!(themes.iter().any(|t| t.name == "midnight"));
        assert_eq!(errors, ["theme broken.toml: foreground is missing"]);
    }
}
