// Generate rudel's function docs from Strudel's jsdoc, as its website builds
// `doc.json` (`npm run jsdoc-json`): the same jsdoc run, config and synonyms
// plugin over the vendored packages, with the jsdoc-json template.
//
// The editor's completion tooltips show what Strudel's autocomplete info panel
// does (codemirror/autocomplete.mjs `Autocomplete`): description, synonyms,
// parameters and examples; and entries tagged `superdirtOnly`/`noAutocomplete`
// are left out of completion, as `hasExcludedTags` leaves them out there.
//
//   cd tools/oracle && npm install   (once, for jsdoc and jsdoc-json)
//   node tools/generate_docs.mjs
// writes crates/rudel-app/src/editor/strudel_docs.rs, a static table.

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const strudel = join(root, 'strudel');
const oracle = join(root, 'tools', 'oracle', 'node_modules');
const tmp = mkdtempSync(join(tmpdir(), 'rudel-docs-'));
const docJson = join(tmp, 'doc.json');
execFileSync(
  process.execPath,
  [
    join(oracle, 'jsdoc', 'jsdoc.js'),
    'packages/',
    '--template',
    join(oracle, 'jsdoc-json'),
    '--destination',
    docJson,
    '-c',
    'jsdoc/jsdoc.config.json',
  ],
  { cwd: strudel, stdio: 'inherit' },
);
const { docs } = JSON.parse(readFileSync(docJson, 'utf8'));
rmSync(tmp, { recursive: true, force: true });

// The HTML jsdoc's markdown plugin produced, as the plain text a tooltip shows.
function text(html) {
  return (html ?? '')
    .replace(/<code>([\s\S]*?)<\/code>/g, '`$1`')
    .replace(/<li>/g, '• ')
    .replace(/<\/(p|li|ul|ol|pre)>/g, '\n')
    .replace(/<br\s*\/?>/g, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&#x27;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

const rust = (s) =>
  '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r/g, '').replace(/\n/g, '\\n') + '"';
const list = (xs) => `&[${xs.map(rust).join(', ')}]`;

// autocomplete.mjs `isValidDoc` / `hasExcludedTags`.
const label = (doc) => doc.name || doc.longname;
const valid = (doc) => label(doc) && !label(doc).startsWith('_') && doc.kind !== 'package';
const excluded = (doc) =>
  ['superdirtOnly', 'noAutocomplete'].some((tag) => doc.tags?.find((t) => t.originalTitle === tag));

const seen = new Set();
const entries = [];
for (const doc of docs) {
  if (!valid(doc) || seen.has(label(doc))) continue;
  seen.add(label(doc));
  const params = (doc.params ?? []).map(
    (p) => `(${rust(p.name ?? '')}, ${rust(p.type?.names?.join(' | ') ?? '')}, ${rust(text(p.description))})`,
  );
  entries.push(
    `    Doc {\n` +
      `        name: ${rust(label(doc))},\n` +
      `        synonyms: ${list(doc.synonyms ?? [])},\n` +
      `        description: ${rust(text(doc.description))},\n` +
      `        params: &[${params.join(', ')}],\n` +
      `        examples: ${list(doc.examples ?? [])},\n` +
      `        excluded: ${excluded(doc)},\n` +
      `    },`,
  );
}

const out = `// Generated by tools/generate_docs.mjs from Strudel's jsdoc; do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later

/// One documented name, as Strudel's \`doc.json\` describes it.
pub(crate) struct Doc {
    pub(crate) name: &'static str,
    pub(crate) synonyms: &'static [&'static str],
    pub(crate) description: &'static str,
    /// \`(name, type, description)\`.
    pub(crate) params: &'static [(&'static str, &'static str, &'static str)],
    pub(crate) examples: &'static [&'static str],
    /// Tagged \`superdirtOnly\` or \`noAutocomplete\`: not offered in completion.
    pub(crate) excluded: bool,
}

pub(crate) static DOCS: &[Doc] = &[
${entries.join('\n')}
];
`;
writeFileSync(join(root, 'crates', 'rudel-app', 'src', 'editor', 'strudel_docs.rs'), out);
console.log(`wrote strudel_docs.rs (${entries.length} docs)`);
