//! Automated Strudel -> Rudel API inventory.
//!
//! Cross-references Strudel's per-package name surface
//! (`tools/oracle/reference_golden.json`, generated by
//! `tools/oracle/gen_reference_oracle.mjs`) against Rudel's live surface
//! (`rudel_lang::reference()`), classifying every documented Strudel name as
//! one of: `implemented`, `intentional` (intentionally different / not
//! applicable), `deferred` (tracked gap), or `unaccounted` (a gap that is
//! neither implemented nor documented — a hard error). The classification uses
//! the same `tools/oracle/reference_allowlist.json` as `reference_parity.rs`.
//!
//! The rendered table is committed at `docs/API_INVENTORY.md`. This test
//! regenerates it and asserts it is byte-identical to the committed copy, so it
//! is both the generator (`RUDEL_BLESS=1` rewrites it) and the drift guard
//! (a plain run fails if the inventory is stale).
//!
//!   RUDEL_BLESS=1 cargo test -p rudel-lang --test api_inventory

use std::collections::{BTreeMap, BTreeSet};

const INVENTORY_PATH: &str = "../../docs/API_INVENTORY.md";

#[derive(Clone, Copy, PartialEq, Eq)]
enum Status {
    Implemented,
    Intentional,
    Deferred,
    Unaccounted,
}

impl Status {
    fn label(self) -> &'static str {
        match self {
            Status::Implemented => "implemented",
            Status::Intentional => "intentional",
            Status::Deferred => "deferred",
            Status::Unaccounted => "unaccounted",
        }
    }
}

/// name -> (status, allowlist-category) from the allowlist, keyed by status.
fn allowlist_index(allowlist: &serde_json::Value) -> BTreeMap<String, (String, String)> {
    let mut out = BTreeMap::new();
    for (category, body) in allowlist["categories"].as_object().unwrap() {
        let status = body["status"].as_str().unwrap().to_string();
        for name in body["names"].as_array().unwrap() {
            out.insert(
                name.as_str().unwrap().to_string(),
                (status.clone(), category.clone()),
            );
        }
    }
    out
}

fn render() -> String {
    let golden: serde_json::Value =
        serde_json::from_str(include_str!("../../../tools/oracle/reference_golden.json")).unwrap();
    let allowlist: serde_json::Value = serde_json::from_str(include_str!(
        "../../../tools/oracle/reference_allowlist.json"
    ))
    .unwrap();

    let r = rudel_lang::reference();
    let mut rudel: BTreeSet<String> = BTreeSet::new();
    rudel.extend(r.functions);
    rudel.extend(r.methods);
    rudel.extend(r.controls);

    let allow = allowlist_index(&allowlist);

    // package -> [name], from the generator's per-name package attribution.
    let mut by_package: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for (name, pkgs) in golden["packagesByName"].as_object().unwrap() {
        for pkg in pkgs.as_array().unwrap() {
            by_package
                .entry(pkg.as_str().unwrap().to_string())
                .or_default()
                .insert(name.clone());
        }
    }

    let classify = |name: &str| -> (Status, Option<&(String, String)>) {
        if rudel.contains(name) {
            (Status::Implemented, None)
        } else if let Some(entry) = allow.get(name) {
            let status = match entry.0.as_str() {
                "unsupported" => Status::Intentional,
                _ => Status::Deferred,
            };
            (status, Some(entry))
        } else {
            (Status::Unaccounted, None)
        }
    };

    let mut out = String::new();
    out.push_str("# Strudel → Rudel API inventory\n\n");
    out.push_str(
        "Generated by `crates/rudel-lang/tests/api_inventory.rs` — do not edit by hand. The \
         Strudel side is `tools/oracle/reference_golden.json` (jsdoc `@name`/`@synonyms` + \
         `register`/`registerControl`, per package); the Rudel side is `rudel_lang::reference()` \
         (live runtime introspection). Each documented Strudel name is classified against \
         `tools/oracle/reference_allowlist.json`:\n\n",
    );
    out.push_str("- **implemented** — exposed by Rudel.\n");
    out.push_str(
        "- **intentional** — intentionally different or not applicable (allowlist status \
         `unsupported`).\n",
    );
    out.push_str(
        "- **deferred** — a tracked gap owned by another checklist item (allowlist status \
         `deferred`).\n",
    );
    out.push_str(
        "- **unaccounted** — neither implemented nor documented; this must never appear.\n\n",
    );
    out.push_str(
        "Regenerate with `RUDEL_BLESS=1 cargo test -p rudel-lang --test api_inventory`. A name \
         defined in more than one Strudel package is listed under each.\n\n",
    );

    // Summary table.
    out.push_str("## Summary\n\n");
    out.push_str("| Package | Names | Implemented | Intentional | Deferred | Unaccounted |\n");
    out.push_str("| --- | ---: | ---: | ---: | ---: | ---: |\n");
    let mut totals = [0usize; 4];
    let mut total_names = 0usize;
    for (pkg, members) in &by_package {
        let mut counts = [0usize; 4];
        for name in members {
            let (status, _) = classify(name);
            let idx = match status {
                Status::Implemented => 0,
                Status::Intentional => 1,
                Status::Deferred => 2,
                Status::Unaccounted => 3,
            };
            counts[idx] += 1;
        }
        for i in 0..4 {
            totals[i] += counts[i];
        }
        total_names += members.len();
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            pkg,
            members.len(),
            counts[0],
            counts[1],
            counts[2],
            counts[3],
        ));
    }
    out.push_str(&format!(
        "| **Total** | **{}** | **{}** | **{}** | **{}** | **{}** |\n\n",
        total_names, totals[0], totals[1], totals[2], totals[3],
    ));

    // Per-package detail tables.
    for (pkg, members) in &by_package {
        out.push_str(&format!("## `{pkg}`\n\n"));
        out.push_str("| Name | Status | Note |\n");
        out.push_str("| --- | --- | --- |\n");
        for name in members {
            let (status, entry) = classify(name);
            let note = entry
                .map(|(_, cat)| cat.replace('_', " "))
                .unwrap_or_default();
            out.push_str(&format!("| `{}` | {} | {} |\n", name, status.label(), note));
        }
        out.push('\n');
    }

    out
}

#[test]
fn api_inventory_is_in_sync() {
    let generated = render();

    // No name may fall through to `unaccounted` — that means a gap exists that
    // neither the runtime nor the allowlist covers.
    assert!(
        !generated.contains("| unaccounted |"),
        "API inventory contains unaccounted names — expose them or add them to \
         reference_allowlist.json (see reference_parity.rs for the exact list)."
    );

    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(INVENTORY_PATH);
    if std::env::var("RUDEL_BLESS").is_ok() {
        std::fs::write(&path, &generated).unwrap();
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    // Normalize CRLF so the check is line-ending agnostic on Windows checkouts.
    let norm = |s: &str| s.replace("\r\n", "\n");
    assert_eq!(
        norm(&committed),
        norm(&generated),
        "docs/API_INVENTORY.md is stale; regenerate with \
         `RUDEL_BLESS=1 cargo test -p rudel-lang --test api_inventory`"
    );
}
