//! Reference-surface parity: compares Strudel's documented reference against
//! Rudel's exposed names.
//!
//! The Strudel side is generated by `tools/oracle/gen_reference_oracle.mjs`
//! (a source-scan of jsdoc `@name`/`@synonyms` tags plus `register` /
//! `registerControl` calls, reproducing the `@strudel/reference` package's
//! `doc.json` name surface without a jsdoc build). The Rudel side is
//! `rudel_lang::reference()`, introspected from the live runtime.
//!
//! Every Strudel-documented name that Rudel does not expose must be listed in
//! `tools/oracle/reference_allowlist.json` with a category/reason. The test
//! asserts the diff equals that allowlist exactly, so a new Strudel name (after
//! regenerating the golden) or a newly added/removed Rudel name fails the test
//! and forces an explicit decision — keeping the comparison honest over time.

use std::collections::BTreeSet;

fn collect(value: &serde_json::Value, key: &str) -> BTreeSet<String> {
    value[key]
        .as_array()
        .unwrap_or(&Vec::new())
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect()
}

/// Flatten every name listed under any category of the allowlist.
fn allowlisted_names(allowlist: &serde_json::Value) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for (_category, body) in allowlist["categories"].as_object().unwrap() {
        for name in body["names"].as_array().unwrap() {
            out.insert(name.as_str().unwrap().to_string());
        }
    }
    out
}

fn rudel_names() -> BTreeSet<String> {
    let r = rudel_lang::reference();
    let mut names = BTreeSet::new();
    names.extend(r.functions);
    names.extend(r.methods);
    names.extend(r.controls);
    names
}

#[test]
fn reference_diff_matches_allowlist() {
    let golden: serde_json::Value =
        serde_json::from_str(include_str!("../../../tools/oracle/reference_golden.json")).unwrap();
    let allowlist: serde_json::Value =
        serde_json::from_str(include_str!("../../../tools/oracle/reference_allowlist.json"))
            .unwrap();

    let strudel = collect(&golden, "names");
    let rudel = rudel_names();
    let allowed = allowlisted_names(&allowlist);

    let missing: BTreeSet<String> = strudel.difference(&rudel).cloned().collect();

    // Names Rudel is missing that aren't yet documented in the allowlist:
    // either expose them or add them with a reason.
    let undocumented: Vec<&String> = missing.difference(&allowed).collect();
    assert!(
        undocumented.is_empty(),
        "Strudel names missing from Rudel and absent from reference_allowlist.json \
         (expose them or document them):\n{undocumented:#?}"
    );

    // Allowlist entries that are no longer missing (Rudel now exposes them, or
    // the name left Strudel): drop them from the allowlist so it stays accurate.
    let stale: Vec<&String> = allowed.difference(&missing).collect();
    assert!(
        stale.is_empty(),
        "reference_allowlist.json lists names that are NOT missing from Rudel \
         (remove these stale entries):\n{stale:#?}"
    );
}

#[test]
fn every_strudel_control_is_exposed_or_allowlisted() {
    // Controls are the most mechanical part of the surface; track them
    // separately so a missing control can't hide inside the combined name diff.
    let golden: serde_json::Value =
        serde_json::from_str(include_str!("../../../tools/oracle/reference_golden.json")).unwrap();
    let allowlist: serde_json::Value =
        serde_json::from_str(include_str!("../../../tools/oracle/reference_allowlist.json"))
            .unwrap();

    let strudel_controls = collect(&golden, "controls");
    // A control name counts as covered if it is reachable in Rudel under any
    // category: a few Strudel control names are exposed by Rudel as helpers
    // instead (e.g. `ds`, which upstream is both a `delaysync` alias and a
    // `register('ds')` envelope helper — Rudel keeps the helper).
    let rudel = rudel_names();
    let allowed = allowlisted_names(&allowlist);

    let missing: Vec<&String> = strudel_controls
        .difference(&rudel)
        .filter(|c| !allowed.contains(*c))
        .collect();
    assert!(
        missing.is_empty(),
        "Strudel controls missing from Rudel and not allowlisted:\n{missing:#?}"
    );
}
